//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication6
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class AdminUser
    {
    	[Required]
    
        public System.Guid AdminUserId { get; set; }
    
        public Nullable<System.Guid> PositionId { get; set; }
    	[Required]
    	[StringLength(50)]
        public string Account { get; set; }
    	[Required]
    	[StringLength(50)]
        public string Pwd { get; set; }
    	[StringLength(50)]
        public string Name { get; set; }
    	[Required]
    
        public System.DateTime CreateTime { get; set; }
    
        public Nullable<int> State { get; set; }
    	[Required]
    	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    				
        public int SortId { get; set; }
    	[StringLength(200)]
        public string Url { get; set; }
    
        public virtual Position Position { get; set; }
    }
}
