//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication6
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class ApplicationforwithdrawalRecord
    {
    	[Required]
    
        public System.Guid Id { get; set; }
    
        public Nullable<System.Guid> GeomanticId { get; set; }
    
        public Nullable<int> Outbizno { get; set; }
    	[StringLength(100)]
        public string Alipayaccount { get; set; }
    	[StringLength(20)]
        public string Realname { get; set; }
    
        public Nullable<decimal> Withdrawalsamount { get; set; }
    
        public Nullable<System.DateTime> Withdrawdate { get; set; }
    
        public Nullable<System.DateTime> Auditdate { get; set; }
    	[StringLength(100)]
        public string Remark { get; set; }
    
        public Nullable<bool> Isaudit { get; set; }
    	[StringLength(200)]
        public string WithdrawalReason { get; set; }
    	[Required]
    	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    				
        public int SortId { get; set; }
    
        public Nullable<bool> IsPay { get; set; }
    
        public Nullable<System.DateTime> PayDate { get; set; }
    
        public Nullable<int> WithdrawAccountType { get; set; }
    	[StringLength(200)]
        public string BankName { get; set; }
    
        public virtual Geomantic Geomantic { get; set; }
    }
}
