//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication6
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class AppVersion
    {
    	[Required]
    
        public int Version { get; set; }
    	[StringLength(50)]
        public string VersionName { get; set; }
    	[StringLength(500)]
        public string AndroidContext { get; set; }
    	[StringLength(500)]
        public string IOSContext { get; set; }
    
        public Nullable<int> Type { get; set; }
    
        public Nullable<int> Size { get; set; }
    }
}
