//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication6
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class Cemetery
    {
        public Cemetery()
        {
            this.CommodityOrder = new HashSet<CommodityOrder>();
            this.Grave = new HashSet<Grave>();
        }
    
    	[Required]
    
        public System.Guid CemeteryId { get; set; }
    	[StringLength(100)]
        public string CemeteryName { get; set; }
    
        public Nullable<System.DateTime> CreateTime { get; set; }
    
        public Nullable<int> SortId { get; set; }
    
        public Nullable<decimal> DeliveryPrice { get; set; }
    	[StringLength(200)]
        public string CemeteryAddress { get; set; }
    
        public Nullable<bool> IsWarehouse { get; set; }
    
        public Nullable<decimal> Proportion { get; set; }
    
        public Nullable<bool> IsDeleted { get; set; }
    
        public Nullable<int> CemeteryType { get; set; }
    
        public Nullable<System.Guid> LyCRMCemteryId { get; set; }
    
        public virtual ICollection<CommodityOrder> CommodityOrder { get; set; }
        public virtual ICollection<Grave> Grave { get; set; }
    }
}
