//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication6
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class CommodityOrder
    {
        public CommodityOrder()
        {
            this.CommissionRecord = new HashSet<CommissionRecord>();
            this.CommodityOrderDetails = new HashSet<CommodityOrderDetails>();
            this.CommodityOrderRefund = new HashSet<CommodityOrderRefund>();
        }
    
    	[Required]
    
        public System.Guid CommodityOrderId { get; set; }
    
        public Nullable<System.Guid> DeliveryTypeId { get; set; }
    
        public Nullable<System.Guid> GeomanticId { get; set; }
    
        public Nullable<System.Guid> CustomerId { get; set; }
    
        public Nullable<System.Guid> DeliveryAddressId { get; set; }
    
        public Nullable<System.Guid> CemeteryId { get; set; }
    
        public Nullable<System.Guid> GraveId { get; set; }
    	[StringLength(50)]
        public string OrderId { get; set; }
    
        public Nullable<int> OrderState { get; set; }
    
        public Nullable<decimal> ActualAmount { get; set; }
    
        public Nullable<decimal> ActualScale { get; set; }
    
        public Nullable<decimal> Totalamount { get; set; }
    
        public Nullable<System.DateTime> BuyingTime { get; set; }
    
        public Nullable<System.DateTime> PayTime { get; set; }
    	[StringLength(20)]
        public string ContactPerson { get; set; }
    	[StringLength(20)]
        public string ContactPhone { get; set; }
    	[StringLength(1000)]
        public string DeliveryTypeJson { get; set; }
    
        public Nullable<bool> IsCustomerCreate { get; set; }
    	[Required]
    	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    				
        public int SortId { get; set; }
    
        public Nullable<System.DateTime> AppointmentTime { get; set; }
    	[StringLength(20)]
        public string PayStyle { get; set; }
    
        public Nullable<System.DateTime> CompleteTime { get; set; }
    
        public Nullable<decimal> FreightFee { get; set; }
    	[StringLength(20)]
        public string ReceiveCode { get; set; }
    
        public Nullable<System.Guid> BurialDepartedId { get; set; }
    
        public Nullable<System.Guid> SecBurialDepartedId { get; set; }
    
        public Nullable<System.Guid> ShareGeomanticId { get; set; }
    	[StringLength(100)]
        public string DepartedCemeteryName { get; set; }
    
        public Nullable<decimal> Proportion { get; set; }
    
        public Nullable<bool> IsNormalSignUp { get; set; }
    
        public Nullable<bool> IsPictrueSignUp { get; set; }
    
        public Nullable<bool> IsVideoSignUp { get; set; }
    
        public virtual Cemetery Cemetery { get; set; }
        public virtual ICollection<CommissionRecord> CommissionRecord { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual DeliveryAddress DeliveryAddress { get; set; }
        public virtual DeliveryType DeliveryType { get; set; }
        public virtual Geomantic Geomantic { get; set; }
        public virtual Grave Grave { get; set; }
        public virtual GraveDeparted GraveDeparted { get; set; }
        public virtual GraveDeparted GraveDeparted1 { get; set; }
        public virtual Geomantic Geomantic1 { get; set; }
        public virtual ICollection<CommodityOrderDetails> CommodityOrderDetails { get; set; }
        public virtual ICollection<CommodityOrderRefund> CommodityOrderRefund { get; set; }
    }
}
