//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication6
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class Commodity
    {
        public Commodity()
        {
            this.CommodityImage = new HashSet<CommodityImage>();
            this.CommoditySpec = new HashSet<CommoditySpec>();
            this.CommodityCommboBind = new HashSet<CommodityCommboBind>();
            this.CommodityOrderDetails = new HashSet<CommodityOrderDetails>();
            this.GeomanticCommodityBind = new HashSet<GeomanticCommodityBind>();
            this.MyFavorites = new HashSet<MyFavorites>();
        }
    
    	[Required]
    
        public System.Guid CommodityId { get; set; }
    
        public Nullable<System.Guid> CategoryId { get; set; }
    	[StringLength(50)]
        public string CommodityName { get; set; }
    	[StringLength(200)]
        public string PictureUrl { get; set; }
    
        public Nullable<decimal> MarketPrice { get; set; }
    
        public Nullable<decimal> SalePrice { get; set; }
    	[StringLength(200)]
        public string TextDetails { get; set; }
    	[StringLength(1000)]
        public string RichTextDetails { get; set; }
    
        public Nullable<int> PurchaseTimes { get; set; }
    
        public Nullable<int> InventoryQuantity { get; set; }
    
        public Nullable<int> SortId { get; set; }
    
        public Nullable<System.DateTime> CreateTime { get; set; }
    
        public Nullable<bool> IsDeleted { get; set; }
    
        public Nullable<decimal> Proportion { get; set; }
    
        public Nullable<int> CommodityType { get; set; }
    
        public Nullable<bool> IsDispInWeb { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<CommodityImage> CommodityImage { get; set; }
        public virtual ICollection<CommoditySpec> CommoditySpec { get; set; }
        public virtual ICollection<CommodityCommboBind> CommodityCommboBind { get; set; }
        public virtual ICollection<CommodityOrderDetails> CommodityOrderDetails { get; set; }
        public virtual ICollection<GeomanticCommodityBind> GeomanticCommodityBind { get; set; }
        public virtual ICollection<MyFavorites> MyFavorites { get; set; }
    }
}
