//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication6
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class CommodityOrderDetails
    {
    	[Required]
    
        public System.Guid CommodityOrderDetailsId { get; set; }
    
        public Nullable<System.Guid> CommodityId { get; set; }
    
        public Nullable<System.Guid> CommodityOrderId { get; set; }
    
        public Nullable<System.Guid> CommoditySpecId { get; set; }
    
        public Nullable<int> Quantity { get; set; }
    
        public Nullable<decimal> CommodityAmount { get; set; }
    	[StringLength(50)]
        public string CommodityName { get; set; }
    	[StringLength(20)]
        public string CommoditySpecName { get; set; }
    	[Required]
    	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    				
        public int SortId { get; set; }
    
        public Nullable<decimal> Proportion { get; set; }
    
        public Nullable<bool> IsSignUp { get; set; }
    
        public Nullable<System.DateTime> SignUpTime { get; set; }
    	[StringLength(1000)]
        public string SacrificeJson { get; set; }
    
        public Nullable<int> CommodityType { get; set; }
    	[StringLength(200)]
        public string SignUpUrl { get; set; }
    
        public Nullable<System.Guid> SignUpUserId { get; set; }
    
        public Nullable<System.Guid> SignUpUserCemeteryId { get; set; }
    
        public virtual Commodity Commodity { get; set; }
        public virtual CommodityOrder CommodityOrder { get; set; }
        public virtual CommoditySpec CommoditySpec { get; set; }
    }
}
