//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication6
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class CommoditySpec
    {
        public CommoditySpec()
        {
            this.CommodityCommboBind = new HashSet<CommodityCommboBind>();
            this.CommodityOrderDetails = new HashSet<CommodityOrderDetails>();
            this.ShoppingCart = new HashSet<ShoppingCart>();
        }
    
    	[Required]
    
        public System.Guid CommoditySpecId { get; set; }
    
        public Nullable<System.Guid> CommodityId { get; set; }
    
        public Nullable<System.Guid> RemoteServiceTemplateId { get; set; }
    	[StringLength(20)]
        public string SpecText { get; set; }
    	[StringLength(200)]
        public string SpecPicture { get; set; }
    
        public Nullable<System.DateTime> CreateTime { get; set; }
    
        public Nullable<int> SortId { get; set; }
    
        public Nullable<bool> IsDeleted { get; set; }
    	[StringLength(1000)]
        public string SacrificeJson { get; set; }
    
        public virtual Commodity Commodity { get; set; }
        public virtual ICollection<CommodityCommboBind> CommodityCommboBind { get; set; }
        public virtual ICollection<CommodityOrderDetails> CommodityOrderDetails { get; set; }
        public virtual RemoteServiceTemplate RemoteServiceTemplate { get; set; }
        public virtual ICollection<ShoppingCart> ShoppingCart { get; set; }
    }
}
