//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication6
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class DeliveryAddress
    {
        public DeliveryAddress()
        {
            this.CommodityOrder = new HashSet<CommodityOrder>();
        }
    
    	[Required]
    
        public System.Guid DeliveryAddressId { get; set; }
    	[StringLength(50)]
        public string StoreName { get; set; }
    	[StringLength(20)]
        public string Phone { get; set; }
    	[StringLength(100)]
        public string Address { get; set; }
    
        public Nullable<int> SortId { get; set; }
    
        public Nullable<bool> IsDeleted { get; set; }
    	[StringLength(200)]
        public string QRCode { get; set; }
    	[Required]
    	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    				
        public int IncreaseId { get; set; }
    
        public virtual ICollection<CommodityOrder> CommodityOrder { get; set; }
    }
}
