//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication6
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class Geomantic
    {
        public Geomantic()
        {
            this.ApplicationforwithdrawalRecord = new HashSet<ApplicationforwithdrawalRecord>();
            this.CommissionRecord = new HashSet<CommissionRecord>();
            this.CommodityOrder = new HashSet<CommodityOrder>();
            this.CommodityOrder1 = new HashSet<CommodityOrder>();
            this.Customer = new HashSet<Customer>();
            this.GeomanticCommodityBind = new HashSet<GeomanticCommodityBind>();
            this.MyFavorites = new HashSet<MyFavorites>();
            this.PromotionRecord = new HashSet<PromotionRecord>();
            this.ShoppingCart = new HashSet<ShoppingCart>();
        }
    
    	[Required]
    
        public System.Guid GeomanticId { get; set; }
    	[StringLength(20)]
        public string Phone { get; set; }
    	[StringLength(50)]
        public string Name { get; set; }
    
        public Nullable<System.DateTime> CreateTime { get; set; }
    	[Required]
    	[StringLength(50)]
        public string Pwd { get; set; }
    
        public Nullable<int> State { get; set; }
    	[StringLength(50)]
        public string hxAccount { get; set; }
    
        public Nullable<System.Guid> ukey { get; set; }
    	[Required]
    	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    				
        public int SortId { get; set; }
    
        public Nullable<decimal> Balance { get; set; }
    
        public Nullable<decimal> Withdraw { get; set; }
    	[StringLength(200)]
        public string QRCode { get; set; }
    
        public Nullable<decimal> DirectProportion { get; set; }
    
        public Nullable<decimal> IndirectProportion { get; set; }
    	[StringLength(200)]
        public string Adress { get; set; }
    	[StringLength(200)]
        public string HeadImgUrl { get; set; }
    
        public Nullable<int> DefaultPayAccountType { get; set; }
    	[StringLength(50)]
        public string WithdrawName { get; set; }
    	[StringLength(50)]
        public string AliAccount { get; set; }
    	[StringLength(20)]
        public string BankUserName { get; set; }
    	[StringLength(50)]
        public string BankAccount { get; set; }
    	[StringLength(20)]
        public string BankName { get; set; }
    	[StringLength(100)]
        public string BankAddress { get; set; }
    
        public Nullable<bool> IsSignAllCommodity { get; set; }
    	[StringLength(100)]
        public string Gesture { get; set; }
    
        public virtual ICollection<ApplicationforwithdrawalRecord> ApplicationforwithdrawalRecord { get; set; }
        public virtual ICollection<CommissionRecord> CommissionRecord { get; set; }
        public virtual ICollection<CommodityOrder> CommodityOrder { get; set; }
        public virtual ICollection<CommodityOrder> CommodityOrder1 { get; set; }
        public virtual ICollection<Customer> Customer { get; set; }
        public virtual ICollection<GeomanticCommodityBind> GeomanticCommodityBind { get; set; }
        public virtual ICollection<MyFavorites> MyFavorites { get; set; }
        public virtual ICollection<PromotionRecord> PromotionRecord { get; set; }
        public virtual ICollection<ShoppingCart> ShoppingCart { get; set; }
    }
}
