//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication6
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class GraveDeparted
    {
        public GraveDeparted()
        {
            this.CommodityOrder = new HashSet<CommodityOrder>();
            this.CommodityOrder1 = new HashSet<CommodityOrder>();
        }
    
    	[Required]
    
        public System.Guid GraveDepartedId { get; set; }
    
        public Nullable<System.Guid> GraveId { get; set; }
    	[StringLength(20)]
        public string DepartedName { get; set; }
    
        public Nullable<System.DateTime> MemorialDay { get; set; }
    
        public Nullable<bool> IsLunarMemorialDay { get; set; }
    
        public Nullable<System.DateTime> BurialTime { get; set; }
    
        public Nullable<bool> IsLunarBurialTime { get; set; }
    
        public Nullable<System.DateTime> CreateTime { get; set; }
    	[Required]
    	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    				
        public int SortId { get; set; }
    
        public virtual ICollection<CommodityOrder> CommodityOrder { get; set; }
        public virtual ICollection<CommodityOrder> CommodityOrder1 { get; set; }
        public virtual Grave Grave { get; set; }
    }
}
