//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication6
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class IdentifyingCode
    {
    	[Required]
    	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    				
        public int IdentifyingCodeId { get; set; }
    	[Required]
    	[StringLength(10)]
        public string Code { get; set; }
    	[Required]
    	[StringLength(20)]
        public string Mobile { get; set; }
    
        public Nullable<System.DateTime> AvailableStartDateTimeUtc { get; set; }
    
        public Nullable<System.DateTime> AvailableEndDateTimeUtc { get; set; }
    
        public Nullable<int> State { get; set; }
    }
}
