 
// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `DefaultConnection`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=.;Initial Catalog=NFineBase;persist security info=True;user id=sa;Password=******;`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;
using System.Data.Entity.ModelConfiguration;
using System.Data.Entity;


namespace NFine.Data
{
    /// <summary>
    /// A class which represents the Sys_RoleAuthorize table.
    /// </summary>
	public partial class Sys_RoleAuthorizeMap:EntityTypeConfiguration<Sys_RoleAuthorize>
	{
		public Sys_RoleAuthorizeMap()
        { 
			this.ToTable("Sys_RoleAuthorize");
			this.HasKey(t => t.F_Id);
		}
	}

    /// <summary>
    /// A class which represents the Sys_Role table.
    /// </summary>
	public partial class Sys_RoleMap:EntityTypeConfiguration<Sys_Role>
	{
		public Sys_RoleMap()
        { 
			this.ToTable("Sys_Role");
			this.HasKey(t => t.F_Id);
		}
	}

    /// <summary>
    /// A class which represents the Sys_Organize table.
    /// </summary>
	public partial class Sys_OrganizeMap:EntityTypeConfiguration<Sys_Organize>
	{
		public Sys_OrganizeMap()
        { 
			this.ToTable("Sys_Organize");
			this.HasKey(t => t.F_Id);
		}
	}

    /// <summary>
    /// A class which represents the Sys_ModuleFormInstance table.
    /// </summary>
	public partial class Sys_ModuleFormInstanceMap:EntityTypeConfiguration<Sys_ModuleFormInstance>
	{
		public Sys_ModuleFormInstanceMap()
        { 
			this.ToTable("Sys_ModuleFormInstance");
			this.HasKey(t => t.F_Id);
		}
	}

    /// <summary>
    /// A class which represents the Sys_ModuleForm table.
    /// </summary>
	public partial class Sys_ModuleFormMap:EntityTypeConfiguration<Sys_ModuleForm>
	{
		public Sys_ModuleFormMap()
        { 
			this.ToTable("Sys_ModuleForm");
			this.HasKey(t => t.F_Id);
		}
	}

    /// <summary>
    /// A class which represents the Sys_ModuleButton table.
    /// </summary>
	public partial class Sys_ModuleButtonMap:EntityTypeConfiguration<Sys_ModuleButton>
	{
		public Sys_ModuleButtonMap()
        { 
			this.ToTable("Sys_ModuleButton");
			this.HasKey(t => t.F_Id);
		}
	}

    /// <summary>
    /// A class which represents the Sys_Module table.
    /// </summary>
	public partial class Sys_ModuleMap:EntityTypeConfiguration<Sys_Module>
	{
		public Sys_ModuleMap()
        { 
			this.ToTable("Sys_Module");
			this.HasKey(t => t.F_Id);
		}
	}

    /// <summary>
    /// A class which represents the Sys_Log table.
    /// </summary>
	public partial class Sys_LogMap:EntityTypeConfiguration<Sys_Log>
	{
		public Sys_LogMap()
        { 
			this.ToTable("Sys_Log");
			this.HasKey(t => t.F_Id);
		}
	}

    /// <summary>
    /// A class which represents the Sys_ItemsDetail table.
    /// </summary>
	public partial class Sys_ItemsDetailMap:EntityTypeConfiguration<Sys_ItemsDetail>
	{
		public Sys_ItemsDetailMap()
        { 
			this.ToTable("Sys_ItemsDetail");
			this.HasKey(t => t.F_Id);
		}
	}

    /// <summary>
    /// A class which represents the Sys_Items table.
    /// </summary>
	public partial class Sys_ItemsMap:EntityTypeConfiguration<Sys_Items>
	{
		public Sys_ItemsMap()
        { 
			this.ToTable("Sys_Items");
			this.HasKey(t => t.F_Id);
		}
	}

    /// <summary>
    /// A class which represents the Sys_FilterIP table.
    /// </summary>
	public partial class Sys_FilterIPMap:EntityTypeConfiguration<Sys_FilterIP>
	{
		public Sys_FilterIPMap()
        { 
			this.ToTable("Sys_FilterIP");
			this.HasKey(t => t.F_Id);
		}
	}

    /// <summary>
    /// A class which represents the Sys_DbBackup table.
    /// </summary>
	public partial class Sys_DbBackupMap:EntityTypeConfiguration<Sys_DbBackup>
	{
		public Sys_DbBackupMap()
        { 
			this.ToTable("Sys_DbBackup");
			this.HasKey(t => t.F_Id);
		}
	}

    /// <summary>
    /// A class which represents the Sys_Area table.
    /// </summary>
	public partial class Sys_AreaMap:EntityTypeConfiguration<Sys_Area>
	{
		public Sys_AreaMap()
        { 
			this.ToTable("Sys_Area");
			this.HasKey(t => t.F_Id);
		}
	}

    /// <summary>
    /// A class which represents the Province table.
    /// </summary>
	public partial class ProvinceMap:EntityTypeConfiguration<Province>
	{
		public ProvinceMap()
        { 
			this.ToTable("Province");
			this.HasKey(t => t.ProvinceId);
		}
	}

    /// <summary>
    /// A class which represents the Sys_UserLogOn table.
    /// </summary>
	public partial class Sys_UserLogOnMap:EntityTypeConfiguration<Sys_UserLogOn>
	{
		public Sys_UserLogOnMap()
        { 
			this.ToTable("Sys_UserLogOn");
			this.HasKey(t => t.F_Id);
		}
	}

    /// <summary>
    /// A class which represents the Sys_User table.
    /// </summary>
	public partial class Sys_UserMap:EntityTypeConfiguration<Sys_User>
	{
		public Sys_UserMap()
        { 
			this.ToTable("Sys_User");
			this.HasKey(t => t.F_Id);
		}
	}

        }
