//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication6
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class OLCommodity
    {
        public OLCommodity()
        {
            this.OLCommodityOrderDetails = new HashSet<OLCommodityOrderDetails>();
            this.OLCommodityBind = new HashSet<OLCommodityBind>();
            this.OLShoppingCart = new HashSet<OLShoppingCart>();
        }
    
    	[Required]
    
        public System.Guid OLCommodityId { get; set; }
    
        public Nullable<System.Guid> OLCategoryId { get; set; }
    	[StringLength(50)]
        public string CommodityName { get; set; }
    
        public Nullable<decimal> MarketPrice { get; set; }
    
        public Nullable<decimal> SalePrice { get; set; }
    	[StringLength(200)]
        public string TextDetails { get; set; }
    	[StringLength(1000)]
        public string RichTextDetails { get; set; }
    
        public Nullable<int> PurchaseTimes { get; set; }
    
        public Nullable<int> InventoryQuantity { get; set; }
    
        public Nullable<int> SortId { get; set; }
    
        public Nullable<System.DateTime> CreateTime { get; set; }
    
        public Nullable<bool> IsDeleted { get; set; }
    	[StringLength(200)]
        public string OnlineMantraPicDisp { get; set; }
    	[StringLength(200)]
        public string OnlineMantraPicPlaced { get; set; }
    	[StringLength(1000)]
        public string ProductHtml { get; set; }
    
        public virtual OLCategory OLCategory { get; set; }
        public virtual ICollection<OLCommodityOrderDetails> OLCommodityOrderDetails { get; set; }
        public virtual ICollection<OLCommodityBind> OLCommodityBind { get; set; }
        public virtual ICollection<OLShoppingCart> OLShoppingCart { get; set; }
    }
}
