//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication6
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class OLCommodityOrderDetails
    {
    	[Required]
    
        public System.Guid OLCommodityOrderDetailsId { get; set; }
    
        public Nullable<System.Guid> OLCommodityOrderId { get; set; }
    
        public Nullable<System.Guid> OLCommodityId { get; set; }
    
        public Nullable<int> Quantity { get; set; }
    
        public Nullable<decimal> CommodityAmount { get; set; }
    	[StringLength(50)]
        public string CommodityName { get; set; }
    	[Required]
    	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    				
        public int SortId { get; set; }
    
        public virtual OLCommodity OLCommodity { get; set; }
        public virtual OLCommodityOrder OLCommodityOrder { get; set; }
    }
}
