//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication6
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class OLGraveDeparted
    {
        public OLGraveDeparted()
        {
            this.OLDepartedBind = new HashSet<OLDepartedBind>();
            this.OLDepartedBind1 = new HashSet<OLDepartedBind>();
        }
    
    	[Required]
    
        public System.Guid OLGraveDepartedId { get; set; }
    
        public Nullable<System.Guid> OLGraveId { get; set; }
    	[StringLength(20)]
        public string DepartedName { get; set; }
    
        public Nullable<System.DateTime> MemorialDay { get; set; }
    
        public Nullable<bool> IsLunarMemorialDay { get; set; }
    
        public Nullable<System.DateTime> BurialTime { get; set; }
    
        public Nullable<bool> IsLunarBurialTime { get; set; }
    
        public Nullable<System.DateTime> CreateTime { get; set; }
    	[Required]
    	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    				
        public int SortId { get; set; }
    
        public virtual ICollection<OLDepartedBind> OLDepartedBind { get; set; }
        public virtual ICollection<OLDepartedBind> OLDepartedBind1 { get; set; }
        public virtual OLGrave OLGrave { get; set; }
    }
}
