//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication6
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class OLGrave
    {
        public OLGrave()
        {
            this.OLGraveDeparted = new HashSet<OLGraveDeparted>();
        }
    
    	[Required]
    
        public System.Guid OLGraveId { get; set; }
    
        public Nullable<System.Guid> OLCemeteryId { get; set; }
    	[StringLength(200)]
        public string GraveNumber { get; set; }
    
        public Nullable<System.DateTime> CreateTime { get; set; }
    	[Required]
    	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    				
        public int SortId { get; set; }
    
        public virtual OLCemetery OLCemetery { get; set; }
        public virtual ICollection<OLGraveDeparted> OLGraveDeparted { get; set; }
    }
}
