//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication6
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class PositionPower
    {
        public PositionPower()
        {
            this.PowerBind = new HashSet<PowerBind>();
        }
    
    	[Required]
    
        public System.Guid PositionPowerId { get; set; }
    
        public Nullable<System.Guid> PositionId { get; set; }
    	[StringLength(50)]
        public string Name { get; set; }
    	[StringLength(200)]
        public string Url { get; set; }
    	[Required]
    	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    				
        public int SortId { get; set; }
    
        public Nullable<System.Guid> Parent { get; set; }
    
        public Nullable<int> MenuCode { get; set; }
    	[StringLength(50)]
        public string DisplayName { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual ICollection<PowerBind> PowerBind { get; set; }
    }
}
