//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication6
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class Region
    {
    	[Required]
    
        public System.Guid RegionId { get; set; }
    
        public Nullable<System.Guid> CityId { get; set; }
    	[StringLength(50)]
        public string RegionName { get; set; }
    
        public Nullable<int> State { get; set; }
    
        public virtual City City { get; set; }
    }
}
