//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication6
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class RemoteTemplateMapping
    {
    	[Required]
    
        public System.Guid RemoteTemplateMappingId { get; set; }
    
        public Nullable<System.Guid> RemoteServiceTemplateId { get; set; }
    
        public Nullable<System.Guid> StepId { get; set; }
    
        public Nullable<int> SortId { get; set; }
    
        public virtual RemotesacrificeServiceStep RemotesacrificeServiceStep { get; set; }
        public virtual RemoteServiceTemplate RemoteServiceTemplate { get; set; }
    }
}
