//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication6
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class SystemLog
    {
    	[Required]
    	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    				
        public int LogId { get; set; }
    	[Required]
    
        public int Type { get; set; }
    	[Required]
    	[StringLength(200)]
        public string Title { get; set; }
    	[StringLength(2000)]
        public string FullMessage { get; set; }
    	[StringLength(50)]
        public string IpAddress { get; set; }
    	[Required]
    
        public System.DateTime CreatedTime { get; set; }
    }
}
