//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication6
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class WeChatAccessToken
    {
    	[Required]
    
        public System.Guid WeChatAccessTokenId { get; set; }
    	[Required]
    	[StringLength(1000)]
        public string AccessToken { get; set; }
    	[Required]
    
        public System.DateTime StartTime { get; set; }
    	[Required]
    
        public System.DateTime EndTime { get; set; }
    
        public Nullable<int> Type { get; set; }
    	[StringLength(50)]
        public string WeChatId { get; set; }
    }
}
